# Generated by Django 4.2.8 on 2023-12-20 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_filmschedules'),
        ('transactions', '0003_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='product',
        ),
        migrations.AddField(
            model_name='transactions',
            name='product_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.filmschedules'),
        ),
    ]
