# Generated by Django 4.2.8 on 2023-12-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transactions_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
