# Generated by Django 4.2.8 on 2023-12-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transactions_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_status',
            field=models.CharField(blank=True, default='unpayments', null=True),
        ),
    ]
