# Generated by Django 4.2.8 on 2023-12-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transactions_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='fraud_status',
            field=models.CharField(blank=True, default='unpayments', null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='payment_type',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
