# Generated by Django 4.2.8 on 2023-12-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transactions_fraud_status_transactions_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='payment_type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
