# Generated by Django 4.2.8 on 2023-12-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_filmschedules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmschedules',
            old_name='product',
            new_name='film_schedules',
        ),
    ]
